
name: ios

on:
  push:
    branches: 
      - master
      - develop
      - release/*
  pull_request:
    branches: 
      - master
      - develop
      - release/*

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: ./SampleCode/iOS

    steps:
      - uses: actions/checkout@v2
